# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: data link
  file:
    state: link
    src: /data
    path: "{{ home }}/data"

- name: vagrant dir
  file:
    state: directory
    path: "{{ home }}/data/vagrant.d"

- name: vagrant link
  file:
    state: link
    src: "{{ home }}/data/vagrant.d"
    path: "{{ home }}/.vagrant.d"

- name: install libvirt packages
  apt:
    install_recommends: no
    name:
      - vagrant-libvirt
      - vagrant-sshfs
      - libvirt-daemon-system
      - qemu-utils
      - qemu-system-x86
  become: yes

- name: add user to the libvirt group
  user:
    append: yes
    name: "{{ user }}"
    groups: libvirt
  become: yes
